- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      docker pull xabhi/ugc-backend:latest
      docker pull xabhi/ugc-frontend:latest

      docker rm -f backend || true
      docker rm -f frontend || true

      docker run -d \
        --name backend \
        --restart always \
        -p 5000:5000 \
        --env-file /home/ubuntu/backend.env \
        xabhi/ugc-backend:latest

      docker run -d \
        --name frontend \
        --restart always \
        -p 5173:5173 \
        xabhi/ugc-frontend:latest

      docker image prune -af